[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]
via_ir=true

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config