[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]
via_ir=true
optimizer = true


[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }



# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config